# Generated by Django 3.0.4 on 2020-04-11 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200410_2039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
